package com.barden.bravo.metrics.type;

/**
 * Statistics.
 */
public enum MetricType {
    ROBLOX_SERVER_OPEN_DURATION,

    FAILED_HEALTH_CHECK_REQUEST,
    FAILED_STATISTICS_UPDATE_REQUEST,
    FAILED_LEADERBOARD_REQUEST,
    FAILED_PLAYER_UPDATES_REQUEST,
    FAILED_PLAYER_UPDATE_REQUEST,
    FAILED_PLAYER_JOIN_REQUEST,
    FAILED_PLAYER_JOIN,

    UNIQUE_PLAYER_JOINED,
    PLAYER_JOINED,
    PLAYER_LEFT,

    GAME_START_TIME,
    GAME_PLAYED,
    ROUND_PLAYED,

    ROBUX_SPENT,
    DONATE,

    GOLD_EARNED,

    PREMIUM_CHEST_OPENED,
    PREMIUM_EGG_OPENED,

    BASIC_CHEST_OPENED,
    BASIC_EGG_OPENED
}
